ControleFinanceiroPessoal/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControleFinanceiroData.DAO;
using ControleFinanceiroData.Entidades;
using ControleFinanceiroData;

namespace ControleFinanceiroPessoal.Controllers
{
    public class CategoriaController : Controller
    {
        // GET: Categoria
        public ActionResult Index()
        {

            loadCategorias();

            return View();
        }

        private void loadCategorias()
        {
            CategoriaDao daoC = new CategoriaDao();
            IList<Categoria> categorias = daoC.Categorias();

            ViewBag.Categorias = categorias;
        }

        [HttpPost]
        public ActionResult Adicionar(Categoria c)
        {
           
            CategoriaDao daoC = new CategoriaDao();

            daoC.Salvar(c);

            //return RedirectToAction("Index","Categoria");
            return Json(c);   
        }

        public ActionResult Remover(int id)
        {
            CategoriaDao daoC = new CategoriaDao();

            Categoria c = daoC.BuscaPorId(id);
            daoC.Remover(c);
            return Json(c);
        }

       

    }
}

ControleFinanceiroPessoal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControleFinanceiroData.DAO;
using ControleFinanceiroData.Entidades;


namespace ControleFinanceiroPessoal.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        //[Route("movimentacoes")]
        public ActionResult Index()
        {
            CategoriaDao categoriaDao = new CategoriaDao();


            IList<Categoria> categorias = categoriaDao.Categorias();

            ViewBag.Categorias = categorias;
            ViewBag.movimentacao = new Movimentacao();
            MovimentacaoDao movimentacaoDao = new MovimentacaoDao();
            IList<Movimentacao> movimentacoes = movimentacaoDao.getMovimetacaoMes();

            ViewBag.SomaMovRec = movimentacaoDao.getTotalEntradaMes();
            ViewBag.SomaMovDesp = movimentacaoDao.getTotalSaidaDoMes();

            ViewBag.TotalDespesa = movimentacaoDao.getDespesaTotal();
            ViewBag.TotalReceita = movimentacaoDao.getReceitaTotal();

            ViewBag.Movimentacoes = movimentacoes;
            
            
            
            return View();
        }
        
    }
}

ControleFinanceiroPessoal/Controllers/MovimentacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControleFinanceiroData.DAO;
using ControleFinanceiroData.Entidades;

namespace ControleFinanceiroPessoal.Controllers
{
    public class MovimentacaoController : Controller
    {
        
        // GET: Home
        //[Route("movimentacoes")]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Form(Movimentacao m)
        {
            MovimentacaoDao movimentacaoDao = new MovimentacaoDao();
            IList<Movimentacao> movimentacoes = movimentacaoDao.getMovimetacaoMes();
            CategoriaDao categoriaDao = new CategoriaDao();
            IList<Categoria> categorias = categoriaDao.Categorias();

            ViewBag.Categorias = categorias;
            return View(movimentacoes);
        }

        [HttpPost]
        public ActionResult Adiciona(Movimentacao movimentacao)
        {
            MovimentacaoDao movimentacaoDAO = new MovimentacaoDao();

            movimentacaoDAO.Adicionar(movimentacao);

            return View();
        }

        
        public ActionResult Remover(int id)
        {
            
            MovimentacaoDao movimentacaoDao = new MovimentacaoDao();
            Movimentacao mov = movimentacaoDao.BuscarPorId(id);

            movimentacaoDao.Remover(mov);

            return Json(mov);

            
        }
    }
}

ControleFinanceiroPessoal/Views/Categoria/Index.cshtml
@using ControleFinanceiroData.Entidades
@model Categoria

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    <script type="text/javascript">
        $("#navcategoria").attr('class', 'active');
        
        jQuery.validator.setDefaults({
            debug: true,
            success: "valid"
        });

        function clicou() {
            var form = $("#myForm");

            form.validate({
                rules: {
                    descricao: {
                        required: true,
                        minlength: 3
                    }
                },
                messages: {
                    descricao: "Informe uma descricão para a categoria"
                }
            });

            enviar(form);
        }
        
        function resposta(data) {
            var newrow = "<tr id=\"categoriaId" + data.Id + "\"><td>" + data.Descricao + "</td><td><a href=\"#\" onclick=\" excluir(" + data.Id + ")\">Excluir</a></td></tr>";

            alert("Nova categoria adicionada");
            $('#tableCategorias tbody').append(newrow);
        }

        function excluir(idCategoria) {
            //alert("Entrou");
            var url = "@Url.Action("Remover", "Categoria")";
            //alert("Url : "+url);
            $.post(url, { id: idCategoria }, atualiza);
        }

        function atualiza(resposta) {
            //console.log("recebeu resposta " + "#categoriaId" + resposta.Id);
            var id = "#categoriaId" + resposta.Id
            $(id).remove();
        }
    </script>


</head>
<body>
    <div class="container">

        <div class="panel panel-default">
            <div class="panel panel-heading">
                <h4>Adicionar Categoria</h4>
            </div>
            <div class="panel panel-body">
                <div hidden="hidden" id="loadM"></div>

                <form id="myForm" action="/Categoria/Adicionar" method="post">
                    <div class="form-group">
                        <label for="descricao">Descrição</label>
                        <input class="form-control" type="text" id="categoria.descricao" name="descricao" />
                    </div>
                    @*<input type="submit" value="Cadastrar" />*@
                </form>
                <div class="form-group">
                    <input class="btn btn-default" type="submit" onclick="clicou();" value="Cadastrar" />
                </div>
            </div>
        </div>
        <h4>Categorias Cadastradas</h4>
        <table id="tableCategorias" class="table table-bordered">
            <thead>
                <tr>
                    <th>Descrição</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var categoria in ViewBag.Categorias)
                {
                    <tr id="categoriaId@(categoria.Id)">
                        <td>@categoria.Descricao</td>
                        <td><a href="#" onclick="excluir(@categoria.Id);">Excluir</a></td>
                        @*<td><a href="/Categoria/Remover/@categoria.Id">Excluir</a></td>*@
                    </tr>
                }
            </tbody>
        </table>

    </div>
</body>

</html>

ControleFinanceiroPessoal/Views/Home/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Página Inicial</title>
    <script type="text/javascript">
        $("#navmov").attr('class', 'active');
        function excluir(idMovimentacao) {

            
            var url = "@Url.Action("Remover", "Movimentacao")";
            console.log("entrou: " + url);
            $.post(url, { id: idMovimentacao }, atualiza);
        }

        function atualiza(reposta){
            var idRow = "#movimentacaoId"+reposta.Id;

            $(idRow).remove();

        }
    </script>
</head>
<body>
    <div class="container"> 
        <div class="col-xs-6">

            <div class="panel panel-default">

                <table class="table table-hover">
                    <thead>
                        <tr class="active">
                            <td>
                                Entradas e Saídas deste mês:
                            </td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="active">
                            <td>
                                Entradas:
                            </td>
                            <td>
                                @ViewBag.SomaMovRec
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                Saídas:
                            </td>
                            <td>
                                @ViewBag.SomaMovDesp
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                Resultado
                            </td>
                            <td>
                                @(@ViewBag.SomaMovRec - @ViewBag.SomaMovDesp)
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-xs-6">
            <div class="panel panel-default">


                <table class="table table-hover">
                    <thead>
                        <tr class="active">
                            <td>
                                Balanço Geral de todos os meses:
                            </td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class="active">
                            <td>
                                Entradas:
                            </td>
                            <td>
                                @ViewBag.TotalReceita
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                Saídas:
                            </td>
                            <td>
                                @ViewBag.TotalDespesa
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                Resultado:
                            </td>
                            <td>
                                @(@ViewBag.TotalReceita - @ViewBag.TotalDespesa)
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="conteudo">
            
            <div class="panel panel-primary">
                
                <div class="panel panel-heading">

                    <div class="panel panel-heading">
                        <h3 align="center">Movimentações do Mês</h3>
                    </div>
                    
                </div>
                <div class="panel panel-body">
                    <table class="table table-bordered" id="movimentacoes">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Descricao</th>
                                <th>Valor</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var movimentacao in ViewBag.Movimentacoes)
                            {
                                <tr id="movimentacaoId@(movimentacao.Id)">
                                    <td>@movimentacao.Id</td>
                                    <td>@movimentacao.Descricao</td>
                                    <td>@movimentacao.Valor</td>
                                    <td><a href="#" onclick="excluir(@movimentacao.Id);">Excluir</a></td>
                                    
                                </tr>

                            }
                            <tr></tr>
                        </tbody>
                    </table>
                    
                </div>
            </div>
             
        </div>
        

        
    </div>

</body>
</html>

ControleFinanceiroPessoal/Views/Movimentacao/Adiciona.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Adiciona</title>
</head>
<body>
    <div> 
        <h1>Movimentacao adicionada com sucesso!</h1>
        @Html.ActionLink("Principal", "Index", "Home")
    </div>
</body>
</html>

ControleFinanceiroPessoal/Views/Movimentacao/Form.cshtml
@model IList<ControleFinanceiroData.Entidades.Movimentacao>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Nova Movimentação</title>
    <script type="text/javascript">
        $("#navnewmov").attr('class', 'active');
        

    </script>
    
</head>

<body>
    <div class="container">
        
        
        <div class="conteudo">

            <div class="panel panel-custom">

                <div class="painel panel-heading" align="center"><h2 id="titulo_mes">Teste</h2></div>
                <div class="painel panel-body">
                    <form action="/Movimentacao/Adiciona" id="novamovimentacao" method="post">
                        <div class="form-group">

                            <td><label for="descricao">Descrição:</label></td>
                            <td><input id="descricao" name="movimentacao.descricao" class="form-control" /></td>


                        </div>
                        <div class="form-group">
                            <td><label for="data">Data</label></td>
                            <td><input id="data" name="movimentacao.data" onfocus="today(this)" maxlength="10" type="text" class="form-control" /></td>
                        </div>



                        <label for="tipo" class="label label-info">Tipo:</label>
                        <div class="radio">
                            <label><input class="form-check" type="radio" name="movimentacao.tipo" value="1" />Receita</label>
                        </div>
                        <div class="radio">
                            <label><input class="form-check" type="radio" name="movimentacao.tipo" value="2" />Despesa</label>
                        </div>

                        <div class="form-group">

                            <label for="categoria">Categoria</label>

                            <select id="categoria" name="movimentacao.CategoriaId" class="form-control">
                                @foreach (var categoria in ViewBag.Categorias)
                                {
                                    <option value="@categoria.Id">@categoria.Descricao</option>
                                }
                            </select>

                        </div>
                        <div class="form-group">
                            <label for="tipo">Valor:</label>
                            R$<input type="number" step="any" id="valor" name="movimentacao.valor" class="form-control" />
                        </div>

                        <div class="form-group">
                            <td><input type="submit" value="Adicionar" class="btn btn-primary" /></td>
                        </div>


                    </form>
                </div>
            </div>
            

            <div class="painel panel-primary">
                <h3 align ="center" >Movimentações do Mês</h3>
                <div class="panel panel-body">
                    <table class="table table-bordered">

                        <tbody>

                            @foreach (var mov in Model)
                            {
                                <tr>
                                    <td>@mov.Id</td>
                                    <td>@mov.Descricao</td>
                                    <td>R$ @mov.Valor</td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>

</body>
</html>

ControleFinanceiroPessoal/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    
    <link rel="stylesheet" href="~/Content/Css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <script src="~/scripts/jquery-3.1.1.min.js"></script>

    
    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.js"></script>


    
    <script type="text/javascript">

        function mascaraData(campoData) {
            var data = campoData.value;
            if (data.length == 2) {
                data += "/";
                document.forms[0].data.value = data;
                return true;
            }
            if (data.length == 5) {
                data += "/";
                document.forms[0].data.value = data;
                return true;
            }
        }
        function onlyNumbers(event) {
            alert("Digitou: " + event.charCode);
            return event.charCode >= 48 && event.charCode <= 57;
        }

        function today(input) {

            console.log(input.name);
            console.log(input.id);

            var today = new Date();
            var day = formatLeftZero(today.getDate());

            var month = formatLeftZero(today.getMonth() + 1);
            var year = today.getFullYear()
            input.value = day + "/" + month + "/" + year;

        }

        function formatLeftZero(number) {
            if (number < 10) {
                number = "0" + number;
            }
            return number;
        }

        $(function () {
            var d = new Date()
            var month = new Array(12);
            month[0] = "January";
            month[1] = "February";
            month[2] = "March";
            month[3] = "April";
            month[4] = "May";
            month[5] = "June";
            month[6] = "July";
            month[7] = "August";
            month[8] = "September";
            month[9] = "October";
            month[10] = "November";
            month[11] = "December";

            var n = month[d.getUTCMonth()];

            $("#titulo_mes").text(n + "/" + d.getFullYear());
        });

        function enviar(form) {

            if (form.valid()) {
                var categoria = form.serialize();

                //var categoria = { descricao:"teste" };
                $.ajax({
                    type: "POST",
                    url: form.attr("action"),
                    data: categoria,
                    datatype: "html",
                    success: function (data) {
                        resposta(data);
                    }
                });

            }
        }

    </script>
</head>
<body>
    <div class="container">
        <div class="page-header">

            <ul class="nav nav-pills pull-right" id="navmenu">
                <li id="navmov">@Html.ActionLink("Movimentações", "Index", "Home")</li>
                <li id="navnewmov">@Html.ActionLink("Nova Movimentacao", "Form", "Movimentacao")</li>
                <li id="navcategoria">@Html.ActionLink("Nova categoria", "Index", "Categoria")</li>
            </ul>
            <h3 class="text-muted">Controle Financeiro Pessoal</h3>
        </div>

    </div>
    @RenderBody();
</body>
</html>